[tool.poetry]
name = "experts_dw"
version = "7.4.1"
description = "Tools for working with the Experts@Minnesota Data Warehouse."
readme = "README.md"
authors = ["David Naughton <naughton@umn.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.3"
cx_oracle = "*"
pugsql = "*"
sqlalchemy = "*"
sqlalchemy_mptt = "*"
sqlparse = "*"

[tool.poetry.dev-dependencies]
alembic = "*"
pytest = "*"
dotenv_switch = {git = "git://github.com/UMNLibraries/dotenv_switch.git"}
pureapi = {git = "git://github.com/UMNLibraries/pureapi.git"}
